# rca_agent.py
# Stage 4 Phase 6: real LLM-based RCA, replacing Week 5's simulated
# if/else threshold logic (week-05/src/rca_agent.py explicitly used
# "simple threshold logic since no ANTHROPIC_API_KEY is set"). Since a
# real API key IS available here (remediation_agent.py already proves
# real Claude calls work in this project), this is an upgrade -- an
# actual LLM reasoning about the incident's real metrics -- not a copy
# of the simulated approach.

import os
import json
from dotenv import load_dotenv
import anthropic

from alert_grouper import Incident

load_dotenv()
client = anthropic.Anthropic()


def synthesize_rca(incident: Incident) -> dict:
    """Makes a real Claude API call, giving it the incident's actual
    grouped peak metrics as context. Returns a dict shaped like Week 5's
    rca_summary (probable_cause, evidence, confidence) so it slots
    directly into stage4-incident.json's rca_summary field -- but this
    time genuinely generated by the model, not selected by a threshold."""

    duration_seconds = (incident.end_time - incident.start_time).total_seconds()

    prompt = f"""You are investigating a real incident on order-svc, a production service.

Incident ID: {incident.incident_id}
Time window: {incident.start_time} to {incident.end_time} ({duration_seconds:.0f} seconds)
Anomalous data points flagged: {incident.point_count}
Peak metrics during the incident:
{json.dumps(incident.peak_metrics, indent=2)}

Based on these real metrics, provide a root cause analysis. Respond with
ONLY a JSON object (no other text, no markdown fences) in exactly this shape:
{{
  "probable_cause": "<one sentence, your best assessment of what caused this>",
  "evidence": ["<specific metric-based evidence point 1>", "<evidence point 2>", "..."],
  "confidence": "<low|medium|high>"
}}"""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )

    raw_text = "".join(block.text for block in response.content if block.type == "text")

    try:
        rca = json.loads(raw_text)
    except json.JSONDecodeError:
        # Real models occasionally wrap JSON in markdown fences despite
        # instructions not to -- strip them before giving up entirely.
        cleaned = raw_text.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        rca = json.loads(cleaned)

    return rca


def write_rca_report(rca: dict, incident: Incident, out_path: str):
    """Human-readable RCA report, same shape as Week 5's, for anyone
    reviewing incidents manually."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    lines = [
        f"# RCA Report -- {incident.incident_id}",
        "",
        f"**Window:** {incident.start_time} to {incident.end_time}",
        f"**Points flagged:** {incident.point_count}",
        f"**Peak metrics:** {incident.peak_metrics}",
        "",
        f"**Probable cause:** {rca['probable_cause']}",
        "",
        "## Evidence",
        *[f"- {e}" for e in rca["evidence"]],
        "",
        f"**Confidence:** {rca['confidence']}",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"[RCA] Wrote {out_path}")


if __name__ == "__main__":
    from anomaly_detector import fetch_real_metrics, fit_detector
    from alert_grouper import group_alerts

    df = fetch_real_metrics(minutes=30)
    result = fit_detector(df, contamination=0.04)
    incidents = group_alerts(result)

    if not incidents:
        print("No anomalies detected in the queried window -- nothing to investigate.")
    else:
        for incident in incidents:
            rca = synthesize_rca(incident)
            write_rca_report(rca, incident, out_path=f"output/rca_report_{incident.incident_id}.md")
            print(f"\n{incident.incident_id}: {rca['probable_cause']} (confidence: {rca['confidence']})")
